SUPPORTED_LANGUAGES = {
    # Latin script languages
    "af": "Afrikaans",
    "az": "Azerbaijani",
    "bs": "Bosnian",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "fr": "French",
    "ga": "Irish",
    "hr": "Croatian",
    "hu": "Hungarian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ku": "Kurdish",
    "la": "Latin",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mi": "Maori",
    "ms": "Malay",
    "mt": "Maltese",
    "nl": "Dutch",
    "no": "Norwegian",
    "oc": "Occitan",
    "pi": "Pali",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "rs_latin": "Serbian (Latin)",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sq": "Albanian",
    "sv": "Swedish",
    "sw": "Swahili",
    "tl": "Filipino",
    "tr": "Turkish",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    # Arabic script languages
    "ar": "Arabic",
    "fa": "Persian",
    "ug": "Uyghur",
    "ur": "Urdu",
    # Bengali script languages
    "bn": "Bengali",
    "as": "Assamese",
    "mni": "Manipuri",
    # Cyrillic script languages
    "ru": "Russian",
    "rs_cyrillic": "Serbian (Cyrillic)",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "uk": "Ukrainian",
    "mn": "Mongolian",
    "abq": "Abaza",
    "ady": "Adyghe",
    "kbd": "Kabardian",
    "ava": "Avar",
    "dar": "Dargwa",
    "inh": "Ingush",
    "che": "Chechen",
    "lbe": "Lak",
    "lez": "Lezghian",
    "tab": "Tabasaran",
    # Devanagari script languages
    "hi": "Hindi",
    "mr": "Marathi",
    "ne": "Nepali",
    "bh": "Bihari",
    "mai": "Maithili",
    "ang": "Angika",
    "bho": "Bhojpuri",
    "mah": "Magahi",
    "sck": "Sadri",
    "new": "Newari",
    "gom": "Goan Konkani",
    "sa": "Sanskrit",
    "bgc": "Haryanvi",
    # Other scripts
    "th": "Thai",
    "ch_sim": "Chinese (Simplified)",
    "ch_tra": "Chinese (Traditional)",
    "ja": "Japanese",
    "ko": "Korean",
    "ta": "Tamil",
    "te": "Telugu",
    "kn": "Kannada",
}
