from .papago import SUPPORTED_LANGUAGES as PAPAGO_SUPPORTED_LANGUAGES
from .google import SUPPORTED_LANGUAGES as GOOGLE_SUPPORTED_LANGUAGES
from .deepl import SUPPORTED_LANGUAGES as DEEPL_SUPPORTED_LANGUAGES
from .baidu import SUPPORTED_LANGUAGES as BAIDU_SUPPORTED_LANGUAGES
from .easyocr import SUPPORTED_LANGUAGES as EASYOCR_SUPPORTED_LANGUAGES

LANGUAGE_SUPPORTS = {
    "PAPAGO": PAPAGO_SUPPORTED_LANGUAGES,
    "GOOGLE": GOOGLE_SUPPORTED_LANGUAGES,
    "DEEPL": DEEPL_SUPPORTED_LANGUAGES,
    "BAIDU": BAIDU_SUPPORTED_LANGUAGES,
    "EASYOCR": EASYOCR_SUPPORTED_LANGUAGES,
}
